post_remove(){
	# .config directory
	rm -f "/etc/skel/.config/autostart/firstrun-desktop.sh"
	rm -f "/etc/skel/.config/autostart/firstrun.desktop"
	rm -f "/etc/skel/.config/autostart/firstrun.sh"

	# .vim
	rm -f "/etc/skel/.vim/autoload/pathogen.vim"
	rm -f "/etc/skel/.vim/colors/monokai.vim"
	rm -f "/etc/skel/.vim/_netrwhist"

	# dot files
	# rm -f "/etc/skel/.bash_logout"
	# rm -f "/etc/skel/.bash_profile"
	# rm -f "/etc/skel/.bashrc"
	rm -f "/etc/skel/.vimrc"
	rm -f "/etc/skel/.xinitrc"
	# rm -f "/etc/skel/.zshrc"

    # User systemd
    rm -f "/etc/skel/.config/systemd/user/ipfs.service"

	# Artwork
	rm -f "/usr/share/brinkOS/logo.png"
	rm -f "/usr/share/brinkOS/icons/logo.png"
	rm -f "/usr/share/brinkOS/icons/icon.png"
	rm -f "/usr/share/brinkOS/icons/logo.svg"
}

pre_upgrade(){
	# .config directory
	rm -f "/etc/skel/.config/autostart/firstrun-desktop.sh"
	rm -f "/etc/skel/.config/autostart/firstrun.desktop"
	rm -f "/etc/skel/.config/autostart/firstrun.sh"

	# .vim
	rm -f "/etc/skel/.vim/autoload/pathogen.vim"
	rm -f "/etc/skel/.vim/colors/monokai.vim"
	rm -f "/etc/skel/.vim/_netrwhist"

	# dot files
	# rm -f "/etc/skel/.bash_logout"
	# rm -f "/etc/skel/.bash_profile"
	# rm -f "/etc/skel/.bashrc"
	rm -f "/etc/skel/.vimrc"
	rm -f "/etc/skel/.xinitrc"
	# rm -f "/etc/skel/.zshrc"

    # User systemd
    rm -f "/etc/skel/.config/systemd/user/ipfs.service"

	# Artwork
	rm -f "/usr/share/brinkOS/logo.png"
	rm -f "/usr/share/brinkOS/icons/logo.png"
	rm -f "/usr/share/brinkOS/icons/icon.png"
	rm -f "/usr/share/brinkOS/icons/logo.svg"
}

