post_remove(){
	# .config directory
	rm -f "/etc/skel/.config/autostart/firstrun-desktop.sh"
	rm -f "/etc/skel/.config/autostart/firstrun.desktop"
	rm -f "/etc/skel/.config/autostart/firstrun.sh"

	# .vim
	rm -f "/etc/skel/.vim/autoload/pathogen.vim"
	rm -f "/etc/skel/.vim/colors/monokai.vim"
	rm -f "/etc/skel/.vim/_netrwhist"

	# dot files
	# rm -f "/etc/skel/.bash_logout"
	# rm -f "/etc/skel/.bash_profile"
	# rm -f "/etc/skel/.bashrc"
	rm -f "/etc/skel/.vimrc"
	# rm -f "/etc/skel/.zshrc"

    # User systemd
    rm -f "/etc/skel/.config/systemd/user/ipfs.service"

    # System wide configs
    if [ -f /etc/mkinitcpio.conf.orig ]; then
        mv "/etc/mkinitcpio.conf.orig" "/etc/mkinitcpio.conf"
    fi

    if [ -f /etc/pacman.conf.orig ]; then
        mv "/etc/pacman.conf.orig" "/etc/pacman.conf"
    fi

	# Artwork
	rm -f "/usr/share/brinkOS/logo.png"
	rm -f "/usr/share/brinkOS/icons/logo.png"
	rm -f "/usr/share/brinkOS/icons/icon.png"
}

pre_upgrade(){
	# .config directory
	rm -f "/etc/skel/.config/autostart/firstrun-desktop.sh"
	rm -f "/etc/skel/.config/autostart/firstrun.desktop"
	rm -f "/etc/skel/.config/autostart/firstrun.sh"

	# .vim
	rm -f "/etc/skel/.vim/autoload/pathogen.vim"
	rm -f "/etc/skel/.vim/colors/monokai.vim"
	rm -f "/etc/skel/.vim/_netrwhist"

	# dot files
	# rm -f "/etc/skel/.bash_logout"
	# rm -f "/etc/skel/.bash_profile"
	# rm -f "/etc/skel/.bashrc"
	rm -f "/etc/skel/.vimrc"
	# rm -f "/etc/skel/.zshrc"

    # User systemd
    rm -f "/etc/skel/.config/systemd/user/ipfs.service"
    
    # System wide configs
    if [ -f /etc/mkinitcpio.conf.orig ]; then
        mv "/etc/mkinitcpio.conf.orig" "/etc/mkinitcpio.conf"
    fi

    if [ -f /etc/pacman.conf.orig ]; then
        mv "/etc/pacman.conf.orig" "/etc/pacman.conf"
    fi

	# Artwork
	rm -f "/usr/share/brinkOS/logo.png"
	rm -f "/usr/share/brinkOS/icons/logo.png"
	rm -f "/usr/share/brinkOS/icons/icon.png"
}

post_upgrade(){
    mv "/etc/mkinitcpio.conf" "/etc/mkinitcpio.conf.orig"
    mv "/etc/pacman.conf" "/etc/pacman.conf.orig"
    
    mv "/etc/mkinitcpio.brinkOS.conf" "/etc/mkinitcpio.conf"
    mv "/etc/pacman.brinkOS.conf" "/etc/pacman.conf"
}

post_install(){
    mv "/etc/mkinitcpio.conf" "/etc/mkinitcpio.conf.orig"
    mv "/etc/pacman.conf" "/etc/pacman.conf.orig"
    
    mv "/etc/mkinitcpio.brinkOS.conf" "/etc/mkinitcpio.conf"
    mv "/etc/pacman.brinkOS.conf" "/etc/pacman.conf"
}
